version: '3.6'

services:
  postgres:
    image: postgres:14.7
    container_name: qhronos_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qhronos
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7.2
    container_name: qhronos_redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: unless-stopped

  qhronosd:
    image: qhronosd:latest
    container_name: qhronosd
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ./config.yml:/app/config.yml
    environment:
      - CONFIG_PATH=/app/config.yml 